config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
end

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top navbar-extend">
  
    <button class="navbar-toggler" data-toggle="collapse" data-target="#menu">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="l-header">
          <i class="fas fa-dumbbell fa-3x"></i>
          <h1>レンタルマッチョ</h1>
      </div>
      <div id="menu" class="collapse navbar-collapse">
      <ul class="navbar-nav navbar-nav-extend ml-auto">
      <li class="nav-item nav-item-extend"><%= link_to "home", root_path, class: "btn btn-primary btn-md btn-extend" %></li>
      <li class="nav-item nav-item-extend"><%= link_to "about", about_path, class: "btn btn-info btn-md btn-extend" %></li>
      <% if logged_in? %>
      <li class="nav-item nav-item-extend"><%= link_to "プロフィール", edit_user_path(current_user), class: "btn btn-secondary btn-md btn-extend" %></li>
      <li class="nav-item nav-item-extend"><%= link_to "マッチョ一覧", users_path(current_user), class: "btn btn-secondary btn-md btn-extend" %></li>
      <li class="nav-item nav-item-extend"><%= link_to "ログアウト", logout_path, method: :delete, class: "btn btn-danger btn-md btn-extend btn-logout-extend" %></li>
      <% else %>
      <li class="nav-item nav-item-extend"><%= link_to "新規登録", signup_path, class: "btn btn-info btn-md btn-extend" %></li>
      <li class="nav-item nav-item-extend"><%= link_to "ログイン", login_path, class: "btn btn-info btn-md btn-extend btn-login-extend" %></li>
      <li><a href="#">ゲストログイン</a></li>
      <li><a href="#">管理ユーザ簡単ログイン</a></li>
      <% end %>
      </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_log.html.erb
<h1 class="log-title col-2">Logs</h1>
<% if @user.microposts.any? %>
  <div class="container">
  
    <ol class="microposts">
    <% @microposts.each do |micropost| %>
      <li id ="micropost-<%= micropost.id %>">
        <span class="row log-list">
          <span class="col-2 log-timestamp d-none d-md-inline-block log-timestamp-block">
            <span class="log-timestamp"><%= time_ago_in_words(micropost.created_at) %>前</span>
          </span>
          <span class="col-md-10 col-log-memos">
            <div class="log-time-and-edit">
              <div class="row">
                
                <span class="col-7 log-timestamp log-timestamp-inline"><%= time_ago_in_words(micropost.created_at) %>前</span>
                <span class="log-edit col-2"><%= link_to image_tag('sample_muscle.jpg', class: "log-edit-image"), edit_micropost_path(micropost) %></span>
              </div>
            </div>
            <% if micropost.content.present? %>
              <div class="log-content"><%= micropost.content %></div>
            <% end %>
            <% if micropost.image.attached? %>
              <div class="log-image"><%= image_tag micropost.resize_image %></div>
            <% end %>
          </span>
        </span>
      </li>
    <% end %>
    </ol>
  </div>

  <%= paginate @microposts, window: 10, outer_window: 1 %>
<% else %>
  <span>まだ投稿がありません</span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <%= tag.div message, class: "alert alert-#{message_type}" %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>